server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

services:
  hosts:
    titan: "https://titan-latest.practo.com"
    book: "https://book-latest.practo.com"
  keys:
    titan: "xxxxxxx"
    book: "xxxxx" 